#!/bin/sh
# fmt-sweep — cargo fmt --all + test + commit + push across N workspaces
#
# Compresses the manual per-repo fmt cycle (8 tool calls × N repos)
# into one invocation. See SKILL.md for the why; this is the body.
#
# Usage:
#   fmt-sweep.sh                       # in-scope default set
#   fmt-sweep.sh --include-lfi         # include the LFI repos
#   fmt-sweep.sh /path/A /path/B ...   # override repo set explicitly
#   fmt-sweep.sh --dry-run             # check drift only; no fmt/commit/push
#
# Exit codes:
#   0  all repos either clean or successfully fmt'd
#   1  test regression post-fmt in at least one repo
#   2  cargo / cargo fmt not installed
#   3  uncommitted non-fmt changes block the sweep

set -eu

INCLUDE_LFI=0
DRY_RUN=0
REPOS=""

for arg in "$@"; do
    case "$arg" in
        --include-lfi)
            INCLUDE_LFI=1 ;;
        --dry-run|-n)
            DRY_RUN=1 ;;
        --help|-h)
            echo "usage: $0 [--include-lfi] [--dry-run] [<repo> ...]"
            exit 0
            ;;
        --*)
            echo >&2 "unknown flag: $arg"
            exit 2
            ;;
        *)
            REPOS="$REPOS $arg" ;;
    esac
done

if ! command -v cargo > /dev/null 2>&1; then
    echo >&2 "error: cargo not found in PATH"
    exit 2
fi
if ! cargo fmt --version > /dev/null 2>&1; then
    echo >&2 "error: cargo fmt not installed"
    echo >&2 "install via: rustup component add rustfmt"
    exit 2
fi

# Default in-scope substrate set. Same defaults as workspace-tests.sh
# so a /loop hygiene cycle can run both with the same effective scope.
if [ -z "$REPOS" ]; then
    if [ -n "${FMT_SWEEP_REPOS:-}" ]; then
        REPOS="$(echo "$FMT_SWEEP_REPOS" | tr ':' ' ')"
    elif [ -f "$HOME/.config/fmt-sweep/repos.txt" ]; then
        REPOS="$(grep -v '^#' "$HOME/.config/fmt-sweep/repos.txt" | grep -v '^$')"
    else
        REPOS="/home/paul/projects/PlausiDen-Forge
/home/paul/projects/PlausiDen-Loom
/home/paul/projects/PlausiDen-Crawler
/home/paul/projects/Crucible"
        if [ "$INCLUDE_LFI" -eq 1 ]; then
            REPOS="$REPOS
/home/paul/projects/PlausiDen-LFI
/home/paul/projects/Forge-LFI"
        fi
    fi
fi

TOTAL_DRIFT=0
REPOS_CLEAN=0
REPOS_SWEPT=0
REPOS_BROKEN=""

run_as_paul() {
    if [ "$(id -u)" -eq 0 ] && id paul > /dev/null 2>&1; then
        sudo -u paul "$@"
    else
        "$@"
    fi
}

for repo in $REPOS; do
    if [ ! -d "$repo" ] || [ ! -f "$repo/Cargo.toml" ]; then
        printf '%-32s\twarn: skipped (path or Cargo.toml missing)\n' "$(basename "$repo")"
        continue
    fi

    NAME="$(basename "$repo")"
    DRIFT="$(run_as_paul cargo fmt --all --check --manifest-path "$repo/Cargo.toml" 2>/dev/null | grep -c '^Diff in' || true)"

    if [ "$DRIFT" -eq 0 ]; then
        printf '%-32s\tclean\n' "$NAME"
        REPOS_CLEAN=$((REPOS_CLEAN + 1))
        continue
    fi

    if [ "$DRY_RUN" -eq 1 ]; then
        printf '%-32s\t%d drift (dry-run; would fmt)\n' "$NAME" "$DRIFT"
        TOTAL_DRIFT=$((TOTAL_DRIFT + DRIFT))
        continue
    fi

    # Apply fmt
    run_as_paul cargo fmt --all --manifest-path "$repo/Cargo.toml"

    # Chown so paul owns any newly-touched files (when running as root)
    if [ "$(id -u)" -eq 0 ] && id paul > /dev/null 2>&1; then
        chown -R paul:paul "$repo"
    fi

    # Verify tests still pass post-fmt
    LOG="/tmp/fmt-sweep-$NAME.log"
    set +e
    run_as_paul cargo test --workspace --manifest-path "$repo/Cargo.toml" > "$LOG" 2>&1
    TEST_EXIT=$?
    set -e

    if [ "$TEST_EXIT" -ne 0 ]; then
        echo "=== $NAME: TEST REGRESSION POST-FMT ==="
        tail -50 "$LOG"
        echo "=== /$NAME ==="
        echo "Reverting fmt changes in $NAME..."
        run_as_paul git -C "$repo" checkout -- '*.rs' || true
        REPOS_BROKEN="$REPOS_BROKEN $NAME"
        printf '%-32s\t%d drift → fmt → tests FAILED → reverted\n' "$NAME" "$DRIFT"
        continue
    fi

    # Stage only .rs files
    RS_FILES="$(run_as_paul git -C "$repo" diff --name-only HEAD | grep '\.rs$' || true)"
    if [ -z "$RS_FILES" ]; then
        printf '%-32s\t%d drift reported but no .rs in diff (anomaly)\n' "$NAME" "$DRIFT"
        continue
    fi

    RS_COUNT="$(echo "$RS_FILES" | wc -l)"
    echo "$RS_FILES" | run_as_paul xargs git -C "$repo" add

    # Commit
    MSG="$(printf 'chore: cargo fmt --all sweep across %s workspace\n\n%d drifted regions across %d .rs files canonicalized in one pass.\nrustfmt is deterministic + idempotent; pure whitespace / line-wrap\nreflow with zero semantic change.\n\nTest verification: cargo test --workspace passes post-fmt.\ncargo fmt --all --check reports 0 drift after the sweep.\n\nGenerated by claude-tools fmt-sweep skill.\n' "$NAME" "$DRIFT" "$RS_COUNT")"
    run_as_paul git -C "$repo" commit -m "$MSG"
    SHA="$(run_as_paul git -C "$repo" rev-parse --short HEAD)"

    # Push
    run_as_paul git -C "$repo" push origin main > /dev/null 2>&1

    printf '%-32s\t%d drift → fmt → tests pass → %s → pushed\n' "$NAME" "$DRIFT" "$SHA"
    TOTAL_DRIFT=$((TOTAL_DRIFT + DRIFT))
    REPOS_SWEPT=$((REPOS_SWEPT + 1))
done

echo "-----"
if [ -n "$REPOS_BROKEN" ]; then
    echo "BROKEN (test regression post-fmt):$REPOS_BROKEN"
    printf 'TOTAL: %d drifted regions across %d swept + %d clean repos\n' "$TOTAL_DRIFT" "$REPOS_SWEPT" "$REPOS_CLEAN"
    exit 1
fi
printf 'TOTAL: %d drifted regions canonicalized across %d repos (%d clean, %d swept)\n' \
    "$TOTAL_DRIFT" $((REPOS_SWEPT + REPOS_CLEAN)) "$REPOS_CLEAN" "$REPOS_SWEPT"
